trigger:
  branches:
    include:
      - main  # تشغيل الـ Pipeline عند أي تحديث في الفرع الرئيسي

pool:
  name: 'Demo'  # تأكدي أن اسم الـ Self-Hosted Agent صحيح

stages:
- stage: Setup
  displayName: 'Setup Environment'
  jobs:
  - job: InstallDependencies
    displayName: 'Install and Cache Dependencies'
    steps:
    - checkout: self  # جلب الكود من GitHub

    - script: |
        python --version
      displayName: 'Verify Python Installation'

    - script: |
        python -m venv venv
      displayName: 'Create Virtual Environment'

    - script: |
        call venv\Scripts\activate
        python -m ensurepip
      displayName: 'Ensure Pip is Installed'


    - task: Cache@2
      inputs:
        key: 'python | "$(Agent.OS)" | requirements.txt'
        path: 'venv'
        cacheHitVar: CACHE_RESTORED
      displayName: 'Cache Python Dependencies'

    - script: |
        call venv\Scripts\activate
        pip install -r requirements.txt
      condition: ne(variables.CACHE_RESTORED, 'true')
      displayName: 'Install Dependencies if Cache Miss'

- stage: Test
  displayName: 'Run Tests in Parallel'
  dependsOn: Setup
  jobs:
  - job: UnitTests
    displayName: 'Run Unit Tests'
    steps:
    - script: |
        call venv\Scripts\activate
        robot -d results/unit_tests AE/Tests/UnitTests
      displayName: 'Execute Unit Tests'

  - job: IntegrationTests
    displayName: 'Run Integration Tests'
    steps:
    - script: |
        call venv\Scripts\activate
        robot -d results/integration_tests AE/Tests/IntegrationTests
      displayName: 'Execute Integration Tests'

- stage: Deploy
  displayName: 'Save and Publish Test Results'
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job: PublishResults
    displayName: 'Publish Test Artifacts'
    steps:
    - publish: $(System.DefaultWorkingDirectory)/results
      artifact: test-results
      displayName: 'Save Test Results'
