trigger:
  - main  # Runs when changes are pushed to the "main" branch
 
pool:
  name: Demo  # Use your self-hosted agent pool
 
steps:
  - script: |
      python --version
    displayName: 'Verify python installation'
 
  - script: |
      python -m venv venv  # Create a virtual environment
      .\venv\Scripts\activate  # Activate the virtual environment (Windows)
      pip install --upgrade pip  # Upgrade pip to the latest version
      pip install pytest  # Install pytest (or other packages you need)
    displayName: 'Install Dependencies'
 
  - script: |
      .\venv\Scripts\activate  # Ensure the virtual environment is activated (Windows)
      pytest tests/  # Run tests
    displayName: 'Run Tests'